name: Pruebas

on:
  push:
    branches:
      - Master
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Build with Maven
        run: mvn test